language: android

before_install:
  - chmod +x gradlew  
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools 
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-27
  licenses:
    - 'android-sdk-license-.+'

script:
  ./gradlew build connectedCheck
