language: android

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools 
    - tools
    - platform-tools
    - build-tools-27.0.1
    - android-27
  licenses:
    - 'android-sdk-license-.+'

script:
  ./gradlew build 
