language: android

before_install:
  - chmod +x gradlew

android:
  components:
    - tools 
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
  licenses:
    - 'android-sdk-license-.+'

script:
  ./gradlew build connectedCheck
